language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - node_modules
jobs:
  include:
    - stage: 'Flow'
      script: npm run flow
    - stage: 'Lint'
      script: npm run linter:js
    - script: npm run linter:css
    - stage: 'Test'
      script: npm test -- --coverage
      after_script: cat coverage/lcov.info | node_modules/.bin/coveralls
