dist: xenial
language: node_js
node_js:
- 11
cache:
  yarn: true
  directories:
  - node_modules
stages:
  - flow
  - lint
  - test
  - security
  - build
  - name: deploy
    if: branch = master AND type IN (push)
jobs:
  include:
  - stage: flow
    script: yarn run flow
  - stage: lint
    script: yarn run linter:js
  - script: yarn run linter:css
  - stage: test
    script: yarn test -- --coverage --maxWorkers=4
    after_script: cat coverage/lcov.info | node_modules/.bin/coveralls
  - stage: security
    script: yarn run audit
  - stage: Build
    before_script:
    - openssl aes-256-cbc -K $encrypted_aa8150b9db17_key -iv $encrypted_aa8150b9db17_iv
      -in deploy_rsa.enc -out deploy_rsa -d
    - chmod 600 deploy_rsa
    script: |
      yarn run build
      find build/static -regextype posix-basic -regex '.*\.\(js\|css\)\(.map\)\?$' -print0 | xargs --null -I@ sh -c "gzip -c @ > @.gz"
      scp -i deploy_rsa -r build $DEPLOY_USER@$DEPLOY_HOST:/tmp/shelf2-${TRAVIS_BUILD_NUMBER}
  - stage: deploy
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_aa8150b9db17_key -iv $encrypted_aa8150b9db17_iv
      -in deploy_rsa.enc -out deploy_rsa -d
    - chmod 600 deploy_rsa
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: ssh -i deploy_rsa $DEPLOY_USER@$DEPLOY_HOST "sh ${DEPLOY_PATH}/bin/promote /tmp/shelf2-${TRAVIS_BUILD_NUMBER} /srv/shelf2_public"
env:
  global:
  - secure: ntaLASfYevkdfmuFRrnkjZ+TXIngNatT0cQXhbEAXL/VGK91I3qOmZbhgKw2dGG9Re02nfWH5emxznHtDNudPKShm4we85zj4ILRtEwSJBj0f7gX5Ahs/SGjE6ZlzAQnnUnaF/Ra+M5pOF7n9jD3l0Nk4tY30unSXFBXKOqSTX//+M8G4wDTIdQCR2ewSvRLimzRRcvnpy4vr86WMntewwpIUMqaN3n9UBBVnOQq3X5E/3gvNpNd2EbH+p76kxUpWacdFQL8qOURGZQKtQCG8YJx9gJqeVHiI8eL7uJ7kgTaz9lVeeLoHwCeNdP3ez36ua/Q8qmcaN+nyi1fcIPnS0RyvFSDcFuxmHRIskMVBdyFtrNsnNJRWZ6YUVfg8NIKI70th4EzScFpaY/F5fINRivbU6dwd+buU/oCg1m4HRRtzDWkalJZLY806OyiA0tCynkUE3pkWL7bMRGtsvhRj6u5V3ZxrKpdz+eRpz+a0/R9seKvlvoD380kKG+yOdxO9Yrw2+tQFbR+lc8xwpAPwspNmsas8bu3Q4NorLZeVk+3a64mXJnPV2hfvwJYuNfScsB0CkHaMrXVwpwemjQZxCXo5TW0zVje9y0aMfvxgjvQtw/vi4eT7m1gFZ8N4e0ZkB0fMGBZG/iWRpyfqvP4NrPFuCaF8i9zvBXL0OfCY24=
  - secure: hzBYtUOMkA5q3uW4kaZxo3ex5oeLr2ZwrdCTN5rxMX4TEgUKrGxe6YJDlF+ohYlhA70MbTrQo6i8xe0xz2wDqKC1AI2HcYRrBPEsfZo7KSrjyAPyAtXBxkG+69rUHRcCpU5fG1os1VFI0LzRY1nuZqa23OZLi8VhWIMk8QnlvTyYkOLsEOBrLR3/7YbkYZYYic8MqJipTwLwzMnHU5x07VHHUY2sSsEKZVw4okZhZbxwjQnpbXewgGnaYNTqdqcR0YQ+ZLdbXel6kkXha+gRYyWwitEqpzfkHGYK0dolNlgksMbP/UvdJLECnRgHJIUjGqSENhVE2GjMfCD/i0zfDtGLl3l4G6fZGO9A7XWg/MSgo8XUorRHPiG0yuutJS+sDSXM2kIKq6rRj0uLaF3r3wm3J3DALNzNAl5OZbfxudfvqye+d9c9fp/1OLtBOw6udPU93l7XplzgsJ7F7BNpqNyrsax0tK+KGQHvWF5p0HXdLHAr9E0Q06o7IogQztTiksgzywJGQQJUFEPmUJvmKdb4No6aq63nhsIzLwYCrqSykVLgzPYXgpHv1Vv4e1QSXBeGP+uu+S84mSBQXVHsM/wKiHohA7oF8kMocRab5PeNG6t/Wrxko4Q9EGFCEJtBYKL/F6jaOHzMooyhsfKje9vIeYwxdzcc5y52EHaQ32g=
  - secure: A6KztC/5kqmTFcCLbfxtT31/l6WHQg3JRhPc30lr7v1rAzCE6j35JuaS7rC4Wvd6SdmTMgQtY83HNbpOWX+qmUOrvO1/KCU/oyWNRDYknJaMBodSxin5oytsH7knES+H1ClSk66f4iAJDOtx17t/MX5+cwCqmpHriBN7G+kA3Pjyx8LYY4Q3PDHLwW4kqTAB3XNKReiJd4MlYTj+j6j0DtrnpSMr4ASLBM+9+8VfrmvPnT/iUCXDc2B5mEnGS3353uPsiktzhiPKeTF+FIc1RF7SwGt3c+LBu+yqDpX7XW7PuV42IT+O/K5z9h/DzhLZ07hqwUUwNj+PRxyOMDokWHZ/5gBB/8vtJ0TFwma/zOnRJIcX8ULrucpBUxTm+WLoUkikKvSwbTg2U1ysyzYn9hDr4LLPVr9Dh4c5fOqCZpJaQ5lUFWkyjt1zduFZf3ZItJvSV+x32ejUa2vLJpUkRGXhmVI6wJJ7iEOLrJKU/qUAx4FI/htvP6wH3F0IJSvEuiMc1kk/Hen7tJ8mVxPrufG9sG/WiiofXsNdjJlmKRet27uAKQQc54Y4GY81ACfjRwCEZT2CqPO/h2TZkO2BA6PQkmoKqS5cH659gAlQVBG+0Y/ZWKAGtyBUq4df4UisE05dyVcHFaDCd+8mIcvLTkgOwghlJhcLNUGYL4CPtvI=
  - secure: CVV0CShZYW7ovbUShlFMfjOeNPNhv22nzVTPAWCRPlflpY2FthVAmWwsm2JlKIXAO2Xn/Ny3x2UCNQPKTYPafUAzkKvD019y7KFYICSw3M8kz8MVNqauLkI2FC2BFgk4Z8HYuvOKvQJopisfW6lycDZZZwq50oBXwvhcUXln0hCULtuCUx/GUhpOY+KdFDVNp8s5HUca8ZSvd13mjtIO34eb6wHVSrUhbtLI9MCH8MVMqie2kCKiaqnF73SW8UzslUms1ZmnCVXqPUHzktrNOumiI5Cz34MmjP64u3O0uBxcbh1l9xxgr1MPXCKTCAue4CkvTHH4FGSTD3NtEr0KYceOG5CSidnT0uUW4fAk4IHz+UkcKXXgMurFVro5DY+1qXQQ23TDr5N8j/OKbsBW3p5PaX03UJTkfLbTV819HMo0TVyDEOGenlE91SrQBs6kXwGOtaZ3MyMs0TD2GTKyFO1RR0I18um883VY1rTWi/+e/fE/i4j/ONXJkwg5pgXLQM7Jv1f8Dpfo5izAr/Wk8RZZp138OAR+INq5MKIfa1xrlbrkwir+Lo2OIvDqjZqkEFQVzJ83ei0grc/EsNGQl2ADwGUbx2KW/fSTbcgPraR7hIoMxEghrVQwEglelhr6iaXauYbfnhOCS/CEtsjQDoW4qIM1NuEg2RNPnSZ7RMg=
  - secure: Lgj80q8dioeg97/p+2/TfVTNOqOcvV4ZPdcPyGSd/QLAJfBjOszjj+WD6TMDKD6OHCNvPWwTt6XDn9DOexGiH9sqaNxRVuf0xO1NcLd88mPBrQ+s8Z5O6sKuGTODTbIX2/A5IqbjwAbUnDpk/4nEzzbLlqJ39FqSLM5ITiaztkYZNJF4HpIE/5hXLgmXDLYOUoIrm0955Hz7K2J7B5/hvp02wkqDV4HJCdGgVn48TYr2YWEcUbX6g+/yJhsHIr5nzVA19r44eUGCTpyf+mTCV26CqE1Q/u4wJ3v30izJkXIZgQdp6pyGUNf903cdwpUAUzwmbciigpZoT9Kr38c+VMNhbj75IxaOuhSi0sHAL4wqzfOhZqc3wnh2HOndWV83zotm3HdYaUkUfSVEqlDBa9emN25/5PPloRNS+9AmXZ9V/UhjqjUAIqO1u0FUFtQTfwYkU/g7eJarsW+tfXcF0uraH+fq5g1jb0NX3CAehP2Fr+EboOG8CmPLtlVVISOIxSl8TkB54UKdj8Y1ZXQvNhgOdRN1lY+m/pu1ljymoRgRSCLz07GlotTGA85PG8wYfw9GGV8jCjzOAKaUN9ugEn+VLXr9Nl0JimmCNXA4kMXbjAfA9wBUjokSuMpm/CF0hVdZAnuB6J5kWXgPGCkxa7OwgMwZDy+a2eentDkCLcA=
  - secure: RzVCqLOk8I+qUqxEj/jtwP3xXUOgvi10q5lobK6qe0aDSSsSQFJzz211gbgvtUtSzX4OrJmdHrPdv5GocV8L2Bd+6Wf2jkvOTIGyLHHWLXF37LNlBfNrf5DxtYjt8Oljmv7gFXWbpV/WZXmZXbZqfoftuYUVy4uEeDMZEJZrsdu365buu2Wg+AbEITOFSaCAc8iyGGgTcj9I3TkC1WX2B+Jk444Ci5Imu/DFTUEaNkkUOd3DrEAaXNLyv1+i8khL6pZ8bHzVQrJe7ofRlcf6nbQRk3fnzWky52dYRJ8Lr2CdLn0W/Dy8CE7oSWJkab/UA/QLwndgWWAFwMoWwEQJqphEyZr9ijxNzZQ9CMtPPHnlNWupZsybJHrmAmDC/6U4AdO5YR/9y2E5SMlNvwkCbqFeT0I9owWjZBpnRW2CQ9D9z5CZGK0Al5CT8dhg52gxKQDD3x5tz1rnFNHUqkA1AcnqwyglmuxdLpYlzhS3go061OmbcngbCFMZob4+BpCYlXkRGfFnHIvojow+EvFjsv8GFOuk9MxpF9vG+AsfUmjDsmezmdhmNphu2ftUGcSIzNd6q2+eZwKqpHm26KHM0UDemoGPwLHZeyXHZZcP9gTP+ZAuLufKA/od4J05N9FE4dlyB9QU6azlCUO/NmsjfeMdnuempOTHT+I2CKXrWHA=
  - secure: A/9bf3aOUs/ZW8EiCN/Wef0HVgvrXMWXjWZTK1bQfoTHeiU2MY56Tg7GFeIlaqevf8n7/qf/Pusmuxmw2a+CluZi2k0gwMHQUgJk1hltRR0Ud9OlLCHa1dkAD8YWaiBCHn6kSe80VIRtLuM257XHwzd9j/riuE9m+cutADwFAHlad0GCOV29kiUdpp10CN+Wl88ceY4Zte0Rjnj7789EwH5vAfXXctxjLGtmpf/l5Rt8DBGmdV6Bcl+qptk6xwwbb1Nl8tRNebp15aiumnZv82ijshC4E+s37XyQZ0cxk3WGPOKIeQXhPXtQarpdvhI2W2QpLv2hpAn1vHXXqnfoPx+DJ9x5X2TRagbomGzWDnF7+xvZCvks88RaG9a18p5JrRcNXxLNkrFW8aRVjUULAvor1Tza3MzfqapTKvKXASSO+SzrsMy/WPy1l5o3R6WcAoAXZluAICNeChsVwrI6ayPRt4B/rp+sOVA5uH1irj+Ln1oPX9u9zdSSL7USeO22eCixoaz4lM/HkJjAQ0EA8H5NhzG1Fkr6Wzp6Wa644Be7o9eXKfCtc8xQy9T/dH1QPz1SpzB0bmT6lYfQVZOh5AO+3YNGt8gW9RJvOv5CAbIbDhSFhm/5x8xE7SEkXlGkC633zzm3xkmXETi6mQWj78TULxK6woUtsVChJLD5Noc=
addons:
  ssh_known_hosts:
    secure: JTofWqYGl15SiHdrtZVD7+JYcmkDRzoZC5ssY45zY83JWV5cVxbDuOQI99ngBldP2Yp0zZkZkinQMwaGS5y0H3+XLBNZR71tO+i7EvKHTYj1F38GkSYDCfz9cM2eFqCktcpJFeB3bPsbycKH2inV1murqWv2uyZ395nJ2rMruG0c0uJdCs2T9QlQdoeCuAuaJ5hqTQeNDwJjaKgMG58h6sai6ac0jFbw4HtTmSja5Xak5ZTPL58cxqDt3UH61H2Xwgpr4G5rwQ4qJdaXnIF56JGR2UvQV8/9bByhFolmK/AFppza0Qug46c/Hqekr4UQfRZ0OEee8Zrc8gt5LmXS5CQ07HXAE4bR+Qy5B6d0BJ0UvA7hbzWbhvAa/ueqhun0IHG4H7uKtlOVEdwAN3+zX0SVwk0qwXEv75MMrt2KFyqJDp2ctvKWLt0bS43imKa7DzZQ5s913g7bVMtGXxF5rRQ66uq504dV2MNol/IPlpyMgAdCcorNkFtaHIkK4ze1dIsn6XwGryOutpkK+Ez1mqhNF2GnD6gPyEOUg8RYhu374GsMOnIfxUmoIUrunttFVQqZBi02DpzH0yaTu5ETWbGjb7/CHCdrKV8Tl5pCL3gZPdHFslUwCnywanV4QMCrUc5gBMySdFe3hKQxlzcqsu90KMFr+Bf7omFlQM0qdi8=
