// flow-typed signature: 1ed7225835151000f69f73b4d17bd62a
// flow-typed version: <<STUB>>/npm-ls-scripts_v^0.1.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-ls-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-ls-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-ls-scripts/bin/cli' {
  declare module.exports: any;
}

declare module 'npm-ls-scripts/lib/ls' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-ls-scripts/bin/cli.js' {
  declare module.exports: $Exports<'npm-ls-scripts/bin/cli'>;
}
declare module 'npm-ls-scripts/index' {
  declare module.exports: $Exports<'npm-ls-scripts'>;
}
declare module 'npm-ls-scripts/index.js' {
  declare module.exports: $Exports<'npm-ls-scripts'>;
}
declare module 'npm-ls-scripts/lib/ls.js' {
  declare module.exports: $Exports<'npm-ls-scripts/lib/ls'>;
}
