// flow-typed signature: f82beedb1e886329868bc71e35348436
// flow-typed version: <<STUB>>/pact_v^4.2.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pact/dist/common/config' {
  declare module.exports: any;
}

declare module 'pact/dist/common/logger' {
  declare module.exports: any;
}

declare module 'pact/dist/common/net' {
  declare module.exports: any;
}

declare module 'pact/dist/common/request' {
  declare module.exports: any;
}

declare module 'pact/dist/dsl/interaction' {
  declare module.exports: any;
}

declare module 'pact/dist/dsl/matchers' {
  declare module.exports: any;
}

declare module 'pact/dist/dsl/mockService' {
  declare module.exports: any;
}

declare module 'pact/dist/dsl/verifier' {
  declare module.exports: any;
}

declare module 'pact/dist/pact-web' {
  declare module.exports: any;
}

declare module 'pact/dist/pact' {
  declare module.exports: any;
}

declare module 'pact/src/common/config' {
  declare module.exports: any;
}

declare module 'pact/src/common/logger' {
  declare module.exports: any;
}

declare module 'pact/src/common/net' {
  declare module.exports: any;
}

declare module 'pact/src/common/request' {
  declare module.exports: any;
}

declare module 'pact/src/dsl/interaction' {
  declare module.exports: any;
}

declare module 'pact/src/dsl/matchers' {
  declare module.exports: any;
}

declare module 'pact/src/dsl/mockService' {
  declare module.exports: any;
}

declare module 'pact/src/dsl/verifier' {
  declare module.exports: any;
}

declare module 'pact/src/pact-web' {
  declare module.exports: any;
}

declare module 'pact/src/pact' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pact/dist/common/config.js' {
  declare module.exports: $Exports<'pact/dist/common/config'>;
}
declare module 'pact/dist/common/logger.js' {
  declare module.exports: $Exports<'pact/dist/common/logger'>;
}
declare module 'pact/dist/common/net.js' {
  declare module.exports: $Exports<'pact/dist/common/net'>;
}
declare module 'pact/dist/common/request.js' {
  declare module.exports: $Exports<'pact/dist/common/request'>;
}
declare module 'pact/dist/dsl/interaction.js' {
  declare module.exports: $Exports<'pact/dist/dsl/interaction'>;
}
declare module 'pact/dist/dsl/matchers.js' {
  declare module.exports: $Exports<'pact/dist/dsl/matchers'>;
}
declare module 'pact/dist/dsl/mockService.js' {
  declare module.exports: $Exports<'pact/dist/dsl/mockService'>;
}
declare module 'pact/dist/dsl/verifier.js' {
  declare module.exports: $Exports<'pact/dist/dsl/verifier'>;
}
declare module 'pact/dist/pact-web.js' {
  declare module.exports: $Exports<'pact/dist/pact-web'>;
}
declare module 'pact/dist/pact.js' {
  declare module.exports: $Exports<'pact/dist/pact'>;
}
declare module 'pact/src/common/config.js' {
  declare module.exports: $Exports<'pact/src/common/config'>;
}
declare module 'pact/src/common/logger.js' {
  declare module.exports: $Exports<'pact/src/common/logger'>;
}
declare module 'pact/src/common/net.js' {
  declare module.exports: $Exports<'pact/src/common/net'>;
}
declare module 'pact/src/common/request.js' {
  declare module.exports: $Exports<'pact/src/common/request'>;
}
declare module 'pact/src/dsl/interaction.js' {
  declare module.exports: $Exports<'pact/src/dsl/interaction'>;
}
declare module 'pact/src/dsl/matchers.js' {
  declare module.exports: $Exports<'pact/src/dsl/matchers'>;
}
declare module 'pact/src/dsl/mockService.js' {
  declare module.exports: $Exports<'pact/src/dsl/mockService'>;
}
declare module 'pact/src/dsl/verifier.js' {
  declare module.exports: $Exports<'pact/src/dsl/verifier'>;
}
declare module 'pact/src/pact-web.js' {
  declare module.exports: $Exports<'pact/src/pact-web'>;
}
declare module 'pact/src/pact.js' {
  declare module.exports: $Exports<'pact/src/pact'>;
}
