// flow-typed signature: f7de5d7823ed163026d6ed84d7c0331d
// flow-typed version: <<STUB>>/react-pluralize_v^1.2.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-pluralize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-pluralize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-pluralize/dist/bundle' {
  declare module.exports: any;
}

declare module 'react-pluralize/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-pluralize/dist/bundle.js' {
  declare module.exports: $Exports<'react-pluralize/dist/bundle'>;
}
declare module 'react-pluralize/index' {
  declare module.exports: $Exports<'react-pluralize'>;
}
declare module 'react-pluralize/index.js' {
  declare module.exports: $Exports<'react-pluralize'>;
}
declare module 'react-pluralize/webpack.config.js' {
  declare module.exports: $Exports<'react-pluralize/webpack.config'>;
}
